# Generated by Django 3.1.5 on 2022-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
