# Generated by Django 3.1.5 on 2022-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='votes_by',
            field=models.TextField(default=''),
        ),
    ]
