# Generated by Django 3.1.5 on 2022-08-03 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0002_auto_20220611_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 21, 31, 11, 841204, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chating.roomname'),
        ),
    ]
