# Generated by Django 3.1.5 on 2022-06-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0002_message_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
