# Generated by Django 3.1.5 on 2022-06-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0003_message_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
