# Generated by Django 3.1.5 on 2022-08-03 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0003_auto_20220803_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomName',
            new_name='Room',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 21, 33, 12, 15197, tzinfo=utc)),
        ),
    ]
