# Generated by Django 3.1.5 on 2022-06-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0004_auto_20220603_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
