# Generated by Django 3.1.5 on 2022-08-03 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0005_auto_20220803_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_name',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 23, 30, 39, 897797, tzinfo=utc)),
        ),
    ]
