# Generated by Django 3.2.16 on 2022-10-18 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0006_auto_20220804_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 10, 22, 6, 605164, tzinfo=utc)),
        ),
    ]
